{{- if .Values.configmap.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "codecc.names.fullname" . }}-task
  labels: {{- include "codecc.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: task
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  application.yml: |-
    {{- include "application-task.yaml" . | nindent 4 -}}
{{- end }}
